import { Channel, TapframePage, Lead } from '../types';

export const INITIAL_CHANNELS: Channel[] = [
  {
    id: 'ch-ali-abdaal',
    user_id: 'user-demo-1',
    name: 'Ali Abdaal',
    handle: '@AliAbdaal',
    platform: 'youtube',
    avatar_url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    banner_url: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1200&auto=format&fit=crop&q=80',
    subscriber_count: '5.2M subscribers',
    description: 'Evidence-based productivity, creator economy, and building a 6-figure online business.',
    primary_color: '#8B5CF6',
    created_at: new Date(Date.now() - 30 * 86400000).toISOString(),
  },
  {
    id: 'ch-maya-growth',
    user_id: 'user-demo-1',
    name: 'Maya Growth & Media',
    handle: '@MayaMarketing',
    platform: 'youtube',
    avatar_url: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    subscriber_count: '840K subscribers',
    description: 'Scale paid ads, Meta campaigns and conversion rate optimization.',
    primary_color: '#EC4899',
    created_at: new Date(Date.now() - 20 * 86400000).toISOString(),
  }
];

export const INITIAL_PAGES: TapframePage[] = [
  {
    id: 'page-business-bundle',
    channel_id: 'ch-ali-abdaal',
    user_id: 'user-demo-1',
    title: '6-Figure Online Business Starter Kit 2026',
    slug: 'business-bundle',
    campaign_name: 'YouTube: How to Build a 6-Figure Business',
    associated_content: {
      type: 'youtube',
      title: 'How to Build a 6-Figure Online Business in 2026',
      video_url: 'https://youtube.com/watch?v=sample1',
      timestamp: '04:35',
    },
    destination_type: 'landing_page',
    status: 'active',
    headline: 'Get My Free 6-Figure Business Blueprint & AI Toolkit',
    subheadline: 'As featured on YouTube. Step-by-step systems, Notion templates, and the exact software stack to start and scale.',
    badge_text: '🔥 Free Download for Viewers',
    hero_image_url: '/assets/youtube-creator-male.png',
    lead_capture_enabled: true,
    lead_capture_placeholder: 'Enter your best email address...',
    lead_capture_button_text: 'Get Instant Access (Free)',
    lead_magnet_title: '6-Figure Blueprint PDF + Notion Template Pack',
    lead_magnet_download_url: 'https://example.com/starter-kit.pdf',
    cta_buttons: [
      {
        id: 'btn-1',
        label: 'Join Part-Time Creator Academy',
        url: 'https://aliabdaal.com',
        variant: 'primary',
      },
      {
        id: 'btn-2',
        label: 'Read Free Productivity Book Summary',
        url: 'https://aliabdaal.com/book',
        variant: 'secondary',
      }
    ],
    social_links: [
      { platform: 'youtube', url: 'https://youtube.com/@AliAbdaal' },
      { platform: 'twitter', url: 'https://twitter.com/aliabdaal' },
      { platform: 'spotify', url: 'https://open.spotify.com' },
      { platform: 'website', url: 'https://aliabdaal.com' }
    ],
    custom_theme: {
      background_color: '#0B0D17',
      accent_color: '#8B5CF6',
      text_color: '#FFFFFF',
      card_style: 'glass',
      qr_style: {
        fg_color: '#000000',
        bg_color: '#FFFFFF',
        frame_style: 'dark_pill',
        callout_text: 'Scan the QR code to get my free bundle on how to grow your business using AI',
      }
    },
    total_scans: 14820,
    unique_visitors: 11940,
    total_clicks: 6840,
    total_leads: 4320,
    created_at: new Date(Date.now() - 14 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: 'page-meta-ads',
    channel_id: 'ch-maya-growth',
    user_id: 'user-demo-1',
    title: 'Meta Ads Master Swipe File & Cheatsheet',
    slug: 'meta-ads-guide',
    campaign_name: 'YouTube: Meta Ads Strategy 2026',
    associated_content: {
      type: 'youtube',
      title: 'How to Grow Your Business Online Using Meta Ads',
      video_url: 'https://youtube.com/watch?v=sample2',
      timestamp: '02:15',
    },
    destination_type: 'landing_page',
    status: 'active',
    headline: 'Steal My Top 10 High-Converting Meta Ad Frameworks',
    subheadline: 'The exact creative formats and hooks generating over 4.8x ROAS for eCommerce & digital brands in 2026.',
    badge_text: '🚀 Meta Ads Accelerator Kit',
    hero_image_url: '/assets/youtube-creator-female.png',
    lead_capture_enabled: true,
    lead_capture_placeholder: 'Where should we email the swipe file?',
    lead_capture_button_text: 'Send Me The Swipe File',
    lead_magnet_title: 'Meta Ads 2026 Framework PDF + 50 Hook Templates',
    lead_magnet_download_url: 'https://example.com/meta-swipe.pdf',
    cta_buttons: [
      {
        id: 'btn-m1',
        label: 'Book a 1-on-1 Growth Consultation',
        url: 'https://calendly.com',
        variant: 'primary',
      },
      {
        id: 'btn-m2',
        label: 'Explore Meta Agency Services',
        url: 'https://example.com/agency',
        variant: 'outline',
      }
    ],
    social_links: [
      { platform: 'youtube', url: 'https://youtube.com' },
      { platform: 'instagram', url: 'https://instagram.com' },
      { platform: 'website', url: 'https://example.com' }
    ],
    custom_theme: {
      background_color: '#13091B',
      accent_color: '#EC4899',
      text_color: '#FFFFFF',
      card_style: 'glass',
      qr_style: {
        fg_color: '#000000',
        bg_color: '#FFFFFF',
        frame_style: 'gradient_border',
        callout_text: 'Scan the QR code to get my FREE bundle on how to grow your business online using Meta Ads',
      }
    },
    total_scans: 8930,
    unique_visitors: 7420,
    total_clicks: 4120,
    total_leads: 2980,
    created_at: new Date(Date.now() - 7 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  },
  {
    id: 'page-podcast-notes',
    channel_id: 'ch-ali-abdaal',
    user_id: 'user-demo-1',
    title: 'Deep Dive Podcast Episode 142 Summary & Resources',
    slug: 'deep-dive-142',
    campaign_name: 'Podcast: Deep Dive Ep 142',
    associated_content: {
      type: 'podcast',
      title: 'Deep Dive Episode 142: Building Wealth in Your 20s & 30s',
      video_url: 'https://youtube.com/watch?v=sample3',
      timestamp: '18:50',
    },
    destination_type: 'landing_page',
    status: 'active',
    headline: 'Download Episode 142 Show Notes & Recommended Reading',
    subheadline: 'All tools, book recommendations, and investment checklists discussed in this episode.',
    badge_text: '🎙️ Episode Exclusive',
    hero_image_url: '/assets/youtube-creator-male.png',
    lead_capture_enabled: true,
    lead_capture_placeholder: 'Your email for the show notes...',
    lead_capture_button_text: 'Download Episode Notes',
    lead_magnet_title: 'Full Transcript & Curated Reading List',
    cta_buttons: [
      {
        id: 'btn-p1',
        label: 'Subscribe on Apple Podcasts',
        url: 'https://podcasts.apple.com',
        variant: 'secondary',
      },
      {
        id: 'btn-p2',
        label: 'Subscribe on Spotify',
        url: 'https://open.spotify.com',
        variant: 'secondary',
      }
    ],
    social_links: [
      { platform: 'youtube', url: 'https://youtube.com' },
      { platform: 'spotify', url: 'https://spotify.com' }
    ],
    custom_theme: {
      background_color: '#0D1117',
      accent_color: '#6366F1',
      text_color: '#FFFFFF',
      card_style: 'minimal',
      qr_style: {
        fg_color: '#000000',
        bg_color: '#FFFFFF',
        frame_style: 'standard',
        callout_text: 'Scan to download Episode 142 Show Notes & Book Checklist',
      }
    },
    total_scans: 5410,
    unique_visitors: 4890,
    total_clicks: 2890,
    total_leads: 1850,
    created_at: new Date(Date.now() - 3 * 86400000).toISOString(),
    updated_at: new Date(Date.now() - 1 * 86400000).toISOString(),
  }
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    page_id: 'page-business-bundle',
    page_title: '6-Figure Online Business Starter Kit 2026',
    campaign_name: 'YouTube: How to Build a 6-Figure Business',
    channel_id: 'ch-ali-abdaal',
    email: 'sarah.connor@gmail.com',
    name: 'Sarah Connor',
    source: 'YouTube TV Scan',
    referrer: 'YouTube Living Room App',
    device: 'mobile',
    country: 'United States',
    city: 'Los Angeles',
    created_at: new Date(Date.now() - 15 * 60000).toISOString(),
  },
  {
    id: 'lead-2',
    page_id: 'page-business-bundle',
    page_title: '6-Figure Online Business Starter Kit 2026',
    campaign_name: 'YouTube: How to Build a 6-Figure Business',
    channel_id: 'ch-ali-abdaal',
    email: 'david.chen@outlook.com',
    name: 'David Chen',
    source: 'YouTube TV Scan',
    referrer: 'YouTube Living Room App',
    device: 'mobile',
    country: 'United Kingdom',
    city: 'London',
    created_at: new Date(Date.now() - 42 * 60000).toISOString(),
  },
  {
    id: 'lead-3',
    page_id: 'page-meta-ads',
    page_title: 'Meta Ads Master Swipe File & Cheatsheet',
    campaign_name: 'YouTube: Meta Ads Strategy 2026',
    channel_id: 'ch-maya-growth',
    email: 'jessica.alba@fashionhub.io',
    name: 'Jessica Alba',
    source: 'YouTube Mobile / TV',
    referrer: 'YouTube TV Cast',
    device: 'mobile',
    country: 'Canada',
    city: 'Toronto',
    created_at: new Date(Date.now() - 110 * 60000).toISOString(),
  },
  {
    id: 'lead-4',
    page_id: 'page-business-bundle',
    page_title: '6-Figure Online Business Starter Kit 2026',
    campaign_name: 'YouTube: How to Build a 6-Figure Business',
    channel_id: 'ch-ali-abdaal',
    email: 'marcus.vance@techventures.co',
    name: 'Marcus Vance',
    source: 'YouTube TV Scan',
    referrer: 'Apple TV YouTube',
    device: 'mobile',
    country: 'Germany',
    city: 'Berlin',
    created_at: new Date(Date.now() - 180 * 60000).toISOString(),
  },
  {
    id: 'lead-5',
    page_id: 'page-meta-ads',
    page_title: 'Meta Ads Master Swipe File & Cheatsheet',
    campaign_name: 'YouTube: Meta Ads Strategy 2026',
    channel_id: 'ch-maya-growth',
    email: 'kevin.novak@agencygrowth.com',
    name: 'Kevin Novak',
    source: 'YouTube TV Scan',
    referrer: 'Roku TV YouTube',
    device: 'mobile',
    country: 'Australia',
    city: 'Sydney',
    created_at: new Date(Date.now() - 320 * 60000).toISOString(),
  },
  {
    id: 'lead-6',
    page_id: 'page-podcast-notes',
    page_title: 'Deep Dive Podcast Episode 142 Summary & Resources',
    campaign_name: 'Podcast: Deep Dive Ep 142',
    channel_id: 'ch-ali-abdaal',
    email: 'elena.rostova@designlab.de',
    name: 'Elena Rostova',
    source: 'Podcast Video Screen',
    referrer: 'YouTube Desktop Scan',
    device: 'mobile',
    country: 'France',
    city: 'Paris',
    created_at: new Date(Date.now() - 480 * 60000).toISOString(),
  },
  {
    id: 'lead-7',
    page_id: 'page-business-bundle',
    page_title: '6-Figure Online Business Starter Kit 2026',
    campaign_name: 'YouTube: How to Build a 6-Figure Business',
    channel_id: 'ch-ali-abdaal',
    email: 'amara.okafor@lagostech.ng',
    name: 'Amara Okafor',
    source: 'YouTube TV Scan',
    referrer: 'Samsung Smart TV YouTube',
    device: 'mobile',
    country: 'Nigeria',
    city: 'Lagos',
    created_at: new Date(Date.now() - 600 * 60000).toISOString(),
  }
];
