import React, { useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import { useApp } from '../lib/context';
import { 
  ArrowLeft, 
  Save, 
  Sparkles, 
  Plus, 
  Trash2, 
  ExternalLink, 
  Tv, 
  Smartphone, 
  Layers, 
  Lock, 
  AlertCircle,
  Link2,
  CheckSquare,
  Square,
  RefreshCw,
  ArrowRight,
  Globe
} from 'lucide-react';
import type { TapframePage, ProductLink } from '../types';
import { QRCodeDisplay } from '../components/QRCodeDisplay';
import { Mascot } from '../components/Mascot';
import { UpgradePaywallModal } from '../components/UpgradePaywallModal';
import { generateUniqueSlug } from '../lib/slug';

const countWords = (text: string): number => {
  if (!text || !text.trim()) return 0;
  return text.trim().split(/\s+/).filter(Boolean).length;
};

const normalizeUrl = (raw: string): string => {
  if (!raw || !raw.trim()) return '';
  const trimmed = raw.trim();
  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
    return trimmed;
  }
  return 'https://' + trimmed;
};

export const PageEditor: React.FC = () => {
  const { id } = useParams<{ id: string }>();
  const isEditing = Boolean(id);
  const { pages, activeChannel, createPage, updatePage, canCreatePage, profile } = useApp();
  const navigate = useNavigate();

  const existingPage = isEditing ? pages.find(p => p.id === id) : null;
  const isPro = profile?.plan === 'pro';

  // 1. Core Meta & Autogenerated Unique Slug
  const [slug, setSlug] = useState(() => {
    if (existingPage?.slug) return existingPage.slug;
    const allSlugs = pages.map(p => p.slug);
    return generateUniqueSlug(allSlugs);
  });
  const [campaignName, setCampaignName] = useState(existingPage?.campaign_name || '');

  // 2. Streamlined Mobile Page Builder Fields
  const [badgeText, setBadgeText] = useState(existingPage?.badge_text || '');
  const [headline, setHeadline] = useState(existingPage?.headline || existingPage?.title || '');
  const [subheadline, setSubheadline] = useState(existingPage?.subheadline || '');

  // 3. Product Links (Free tier: max 1 link, Pro tier: unlimited)
  const [productLinks, setProductLinks] = useState<ProductLink[]>(() => {
    if (existingPage?.product_links && existingPage.product_links.length > 0) {
      return existingPage.product_links;
    }
    if (existingPage?.cta_buttons && existingPage.cta_buttons.length > 0) {
      return existingPage.cta_buttons.map(b => ({ id: b.id, title: b.label, url: b.url }));
    }
    return [];
  });

  // 4. Email Lead Capture & Field Selection
  const [leadCaptureEnabled, setLeadCaptureEnabled] = useState(
    existingPage?.lead_capture_enabled !== undefined ? existingPage.lead_capture_enabled : true
  );
  const [collectName, setCollectName] = useState(
    existingPage?.lead_capture_fields?.collect_name || false
  );
  const [collectPhone, setCollectPhone] = useState(
    existingPage?.lead_capture_fields?.collect_phone || false
  );
  const [leadMagnetTitle, setLeadMagnetTitle] = useState(
    existingPage?.lead_magnet_title || ''
  );
  const [leadCaptureButtonText, setLeadCaptureButtonText] = useState(
    existingPage?.lead_capture_button_text || ''
  );

  const [saving, setSaving] = useState(false);
  const [errorMessage, setErrorMessage] = useState<string | null>(null);
  const [previewTab, setPreviewTab] = useState<'mobile' | 'qr'>('mobile');
  const [showPaywallModal, setShowPaywallModal] = useState(false);
  const [paywallReason, setPaywallReason] = useState<{ title: string; desc: string }>({
    title: 'Unlock Unlimited Product Links',
    desc: 'Free tier includes 1 product link per Tapframe. Upgrade to Pro to add unlimited product links, Notion hubs, courses, and tools.'
  });

  // Check if free limit blocks creation of a 2nd page
  const isBlockedByFreeLimit = !isEditing && !canCreatePage;

  const handleAddProductLink = () => {
    if (!isPro && productLinks.length >= 1) {
      setPaywallReason({
        title: 'Unlock Unlimited Product Links',
        desc: 'Free tier allows 1 product link per Tapframe. Upgrade to Clearpath Pro to add unlimited product and resource links.'
      });
      setShowPaywallModal(true);
      return;
    }
    setErrorMessage(null);
    setProductLinks([
      ...productLinks,
      { id: Date.now().toString(), title: '', url: '' }
    ]);
  };

  const handleRemoveProductLink = (index: number) => {
    setProductLinks(productLinks.filter((_, i) => i !== index));
  };

  const handleUpdateProductLink = (index: number, field: 'title' | 'url', value: string) => {
    const updated = [...productLinks];
    updated[index][field] = value;
    setProductLinks(updated);
  };

  const handleRegenerateSlug = () => {
    const allSlugs = pages.map(p => p.slug);
    setSlug(generateUniqueSlug(allSlugs));
  };

  // Word limits (Max 100 words)
  const MAX_WORDS = 100;
  const headlineWords = countWords(headline);
  const subheadlineWords = countWords(subheadline);

  const handleHeadlineChange = (val: string) => {
    const words = countWords(val);
    if (words <= MAX_WORDS || val.length < headline.length) {
      setHeadline(val);
    }
  };

  const handleSubheadlineChange = (val: string) => {
    const words = countWords(val);
    if (words <= MAX_WORDS || val.length < subheadline.length) {
      setSubheadline(val);
    }
  };

  const computedTitle = headline.trim() || campaignName.trim() || 'My Video Resource Page';

  const previewPage: TapframePage = {
    id: existingPage?.id || 'temp-id',
    channel_id: activeChannel?.id || 'ch-1',
    user_id: 'user-1',
    title: computedTitle,
    slug: slug || 'my-offer',
    campaign_name: campaignName || `${activeChannel?.name || 'Main'} Campaign`,
    destination_type: 'landing_page',
    external_url: '',
    status: 'active',
    badge_text: badgeText,
    headline: headline || 'Get My Free Resource Kit',
    subheadline: subheadline || 'Drop your email below to unlock instant access to all video tools.',
    product_links: productLinks.map(p => ({ ...p, url: normalizeUrl(p.url) })),
    lead_capture_enabled: leadCaptureEnabled,
    lead_capture_fields: {
      collect_email: true,
      collect_name: collectName,
      collect_phone: collectPhone,
    },
    lead_magnet_title: leadMagnetTitle || 'Free Strategy Guide & Template',
    lead_capture_button_text: leadCaptureButtonText || 'Get Access',
    custom_theme: {
      background_color: '#0B0D17',
      accent_color: activeChannel?.primary_color || '#8B5CF6',
      text_color: '#FFFFFF',
      card_style: 'glass',
      qr_style: {
        fg_color: '#000000',
        bg_color: '#FFFFFF',
        frame_style: 'dark_pill',
        callout_text: headline ? `Scan to get: ${headline}` : 'Scan the QR code to get free access',
      }
    },
    total_scans: existingPage?.total_scans || 0,
    unique_visitors: existingPage?.unique_visitors || 0,
    total_clicks: existingPage?.total_clicks || 0,
    total_leads: existingPage?.total_leads || 0,
    created_at: existingPage?.created_at || new Date().toISOString(),
    updated_at: new Date().toISOString(),
  };

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();

    if (isBlockedByFreeLimit) {
      setPaywallReason({
        title: 'Unlimited QR Tapframes',
        desc: 'Free tier allows 1 active QR Tapframe. Upgrade to Pro to create unlimited dynamic QR pages.'
      });
      setShowPaywallModal(true);
      return;
    }

    setSaving(true);
    setErrorMessage(null);

    // Clean and normalize all product links
    const cleanedLinks = productLinks
      .filter(l => l.title.trim() || l.url.trim())
      .map(l => ({
        ...l,
        title: l.title.trim(),
        url: normalizeUrl(l.url)
      }));

    const payload: Partial<TapframePage> = {
      title: computedTitle,
      slug: slug.trim(),
      campaign_name: campaignName.trim() || `${activeChannel?.name || 'Main'} Campaign`,
      destination_type: 'landing_page',
      external_url: '',
      badge_text: badgeText.trim(),
      headline: headline.trim() || 'Exclusive Video Offer',
      subheadline: subheadline.trim(),
      product_links: cleanedLinks,
      lead_capture_enabled: leadCaptureEnabled,
      lead_capture_fields: {
        collect_email: true,
        collect_name: collectName,
        collect_phone: collectPhone,
      },
      lead_magnet_title: leadMagnetTitle.trim(),
      lead_capture_button_text: leadCaptureButtonText.trim(),
      custom_theme: previewPage.custom_theme,
    };

    try {
      if (isEditing && id) {
        await updatePage(id, payload);
      } else {
        await createPage(payload);
      }
      navigate('/dashboard');
    } catch (err: any) {
      console.error('Error saving page:', err);
      if (err.message === 'FREE_TIER_LIMIT_REACHED') {
        setPaywallReason({
          title: 'Free Tier Limit Reached',
          desc: 'You already have 1 active QR Tapframe on the Free Tier. Upgrade to Pro for unlimited Tapframes.'
        });
        setShowPaywallModal(true);
      } else {
        navigate('/dashboard');
      }
    } finally {
      setSaving(false);
    }
  };

  const primaryProduct = productLinks[0];

  return (
    <div className="space-y-6 animate-fade-in pb-12 w-full max-w-7xl mx-auto">
      {/* Top action header (Apple Minimalist) */}
      <div className="flex items-center justify-between gap-3 pb-3 border-b border-white/[0.08]">
        <div className="flex items-center gap-3 min-w-0">
          <Link
            to="/dashboard"
            className="p-2.5 rounded-2xl bg-white/[0.04] hover:bg-white/[0.08] text-slate-300 hover:text-white transition-colors shrink-0"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div className="min-w-0">
            <span className="text-[10px] uppercase font-bold tracking-widest text-violet-400 block truncate">
              {isEditing ? 'Edit QR Tapframe' : 'Create New QR Tapframe'}
            </span>
            <h1 className="text-base sm:text-2xl font-black text-white truncate">
              {headline || computedTitle}
            </h1>
          </div>
        </div>

        <button
          type="button"
          onClick={handleSave}
          disabled={saving}
          className="px-4 sm:px-6 py-2.5 rounded-2xl bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 disabled:opacity-50 text-white font-bold text-xs sm:text-sm shadow-xl shadow-violet-600/25 flex items-center gap-2 transition-all hover:scale-105 active:scale-[0.98] shrink-0 cursor-pointer"
        >
          <Save className="w-4 h-4" />
          <span className="hidden sm:inline">{saving ? 'Saving...' : 'Save & Publish QR'}</span>
          <span className="sm:hidden">{saving ? 'Saving...' : 'Save'}</span>
        </button>
      </div>

      {isBlockedByFreeLimit && (
        <div className="p-4 rounded-2xl bg-rose-950/60 border border-rose-500/40 text-rose-200 text-xs flex flex-col sm:flex-row sm:items-center justify-between gap-3">
          <div className="flex items-center gap-2">
            <Lock className="w-4 h-4 text-rose-400 shrink-0" />
            <span><strong>Free Tier Limit (1 Tapframe):</strong> You have 1 active QR link. Upgrade to Pro for unlimited pages.</span>
          </div>
          <button 
            type="button"
            onClick={() => {
              setPaywallReason({
                title: 'Unlimited QR Tapframes',
                desc: 'Free tier allows 1 active QR Tapframe. Upgrade to Pro to create unlimited dynamic QR pages.'
              });
              setShowPaywallModal(true);
            }}
            className="px-3.5 py-1.5 rounded-xl bg-violet-600 hover:bg-violet-500 text-white font-bold text-xs whitespace-nowrap cursor-pointer self-start sm:self-auto"
          >
            Upgrade to Pro
          </button>
        </div>
      )}

      {errorMessage && (
        <div className="p-3.5 rounded-2xl bg-rose-950/60 border border-rose-500/40 text-rose-300 text-xs flex items-center gap-2 animate-in fade-in">
          <AlertCircle className="w-4 h-4 shrink-0" />
          <span>{errorMessage}</span>
        </div>
      )}

      {/* Main 2-Column Responsive Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 lg:gap-8 items-start">
        {/* Left Form Editor */}
        <div className="lg:col-span-7 space-y-6">
          <form onSubmit={handleSave} className="space-y-6">
            {/* 1. Core Page & Guaranteed Unique URL */}
            <div className="p-5 sm:p-6 rounded-3xl bg-[#10121E] border border-white/[0.08] space-y-4 shadow-xl">
              <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-violet-400">
                <Layers className="w-4 h-4" />
                <span>1. Core Page & Guaranteed Unique URL</span>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block text-xs font-medium text-slate-300 mb-1.5">Campaign Name (For Leads grouping)</label>
                  <input
                    type="text"
                    maxLength={100}
                    value={campaignName}
                    onChange={(e) => setCampaignName(e.target.value)}
                    placeholder="e.g. YouTube: Six Figure Wealth"
                    className="w-full px-3.5 py-2.5 rounded-2xl bg-[#090A12] border border-white/[0.08] text-white text-xs sm:text-sm placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                  />
                </div>

                <div>
                  <div className="flex items-center justify-between mb-1.5">
                    <label className="text-xs font-medium text-slate-300">Autogenerated Unique Slug</label>
                    <button
                      type="button"
                      onClick={handleRegenerateSlug}
                      className="text-[11px] text-violet-400 hover:text-violet-300 flex items-center gap-1 cursor-pointer"
                      title="Generate new unique slug"
                    >
                      <RefreshCw className="w-3 h-3" />
                      <span>Regenerate</span>
                    </button>
                  </div>
                  <div className="flex items-center rounded-2xl bg-[#090A12] border border-white/[0.08] px-3">
                    <span className="text-xs text-slate-500 font-mono">qr.clearpath.click/q/</span>
                    <input
                      type="text"
                      required
                      readOnly
                      value={slug}
                      className="w-full py-2.5 pl-1 bg-transparent text-emerald-400 text-xs sm:text-sm font-mono focus:outline-none cursor-default font-bold"
                    />
                  </div>
                  <p className="text-[10px] text-slate-500 mt-1">Unique collision-resistant URL slug guaranteed for this QR code.</p>
                </div>
              </div>
            </div>

            {/* 2. Streamlined Mobile Landing Page Builder */}
            <div className="p-5 sm:p-6 rounded-3xl bg-[#10121E] border border-white/[0.08] space-y-4 sm:space-y-5 shadow-xl">
              <div className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-violet-400">
                <Smartphone className="w-4 h-4" />
                <span>2. Mobile Page Content</span>
              </div>

              {/* Badge / Callout Ribbon */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-xs font-medium text-slate-300">Badge / Callout Ribbon</label>
                  <span className="text-[10px] text-slate-500">{countWords(badgeText)}/15 words</span>
                </div>
                <input
                  type="text"
                  maxLength={80}
                  value={badgeText}
                  onChange={(e) => {
                    if (countWords(e.target.value) <= 15 || e.target.value.length < badgeText.length) {
                      setBadgeText(e.target.value);
                    }
                  }}
                  placeholder="e.g. Get the Free Package Below"
                  className="w-full px-3.5 py-2.5 rounded-2xl bg-[#090A12] border border-white/[0.08] text-white text-xs placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                />
              </div>

              {/* Main Headline (Max 100 words) */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-xs font-medium text-slate-300">Main Headline *</label>
                  <span className={`text-[10px] font-mono ${headlineWords >= 95 ? 'text-amber-400' : 'text-slate-500'}`}>
                    {headlineWords}/{MAX_WORDS} words
                  </span>
                </div>
                <input
                  type="text"
                  required
                  value={headline}
                  onChange={(e) => handleHeadlineChange(e.target.value)}
                  placeholder="e.g. The Six Figure Wealth Guide"
                  className="w-full px-3.5 py-2.5 rounded-2xl bg-[#090A12] border border-white/[0.08] text-white text-xs sm:text-sm font-semibold placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                />
              </div>

              {/* Subheadline / Description (Max 100 words) */}
              <div>
                <div className="flex items-center justify-between mb-1.5">
                  <label className="text-xs font-medium text-slate-300">Subheadline / Description</label>
                  <span className={`text-[10px] font-mono ${subheadlineWords >= 95 ? 'text-amber-400' : 'text-slate-500'}`}>
                    {subheadlineWords}/{MAX_WORDS} words
                  </span>
                </div>
                <textarea
                  rows={2}
                  value={subheadline}
                  onChange={(e) => handleSubheadlineChange(e.target.value)}
                  placeholder="e.g. Drop your email below to get the free downloadable guide and resources."
                  className="w-full px-3.5 py-2.5 rounded-2xl bg-[#090A12] border border-white/[0.08] text-white text-xs placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                />
              </div>

              {/* Product Destination Links Section */}
              <div className="p-4 rounded-2xl bg-[#090A12] border border-white/[0.08] space-y-3">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-xs font-bold text-white flex items-center gap-1.5">
                      <Link2 className="w-3.5 h-3.5 text-violet-400" />
                      <span>Product Destination Link</span>
                    </div>
                    <div className="text-[11px] text-slate-400">
                      {isPro ? 'Add unlimited product & resource links.' : 'Free tier allows 1 product link.'}
                    </div>
                  </div>

                  <button
                    type="button"
                    onClick={handleAddProductLink}
                    className="px-3 py-1.5 rounded-xl bg-violet-600/25 hover:bg-violet-600/35 border border-violet-500/35 text-violet-300 text-xs font-semibold flex items-center gap-1 cursor-pointer transition-colors"
                  >
                    <Plus className="w-3.5 h-3.5" />
                    <span>Add Link</span>
                  </button>
                </div>

                {productLinks.length === 0 ? (
                  <div className="p-3.5 text-center text-xs text-slate-500 border border-dashed border-white/10 rounded-2xl">
                    No product link added. Click "+ Add Link" to set the destination URL where visitors are sent after clicking Get Access.
                  </div>
                ) : (
                  <div className="space-y-3 pt-1">
                    {productLinks.map((link, idx) => (
                      <div key={link.id || idx} className="p-3.5 rounded-2xl bg-[#10121E] border border-white/[0.08] space-y-2.5 relative">
                        <div className="flex items-center justify-between">
                          <span className="text-[11px] font-bold text-violet-300">
                            {idx === 0 ? 'Primary Destination Link #1' : `Product Link #${idx + 1}`}
                          </span>
                          <button
                            type="button"
                            onClick={() => handleRemoveProductLink(idx)}
                            className="text-slate-500 hover:text-rose-400 p-1 cursor-pointer"
                            title="Remove link"
                          >
                            <Trash2 className="w-3.5 h-3.5" />
                          </button>
                        </div>

                        <div>
                          <input
                            type="text"
                            maxLength={80}
                            value={link.title}
                            onChange={(e) => handleUpdateProductLink(idx, 'title', e.target.value)}
                            placeholder="Name of the product (e.g. Notion Business Template)"
                            className="w-full px-3 py-2 rounded-xl bg-[#090A12] border border-white/[0.08] text-white text-xs placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                          />
                        </div>

                        <div>
                          <div className="relative">
                            <Globe className="w-3.5 h-3.5 text-slate-500 absolute left-3 top-2.5" />
                            <input
                              type="text"
                              value={link.url}
                              onChange={(e) => handleUpdateProductLink(idx, 'url', e.target.value)}
                              placeholder="e.g. https://creator.gumroad.com or www.yalo.ng"
                              className="w-full pl-9 pr-3 py-2 rounded-xl bg-[#090A12] border border-white/[0.08] text-white text-xs font-mono placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                            />
                          </div>
                          <p className="text-[10px] text-slate-500 mt-1 pl-1">
                            Accepts any URL: <code>https://...</code>, <code>www.domain.com</code>, or <code>domain.com</code> (auto-prefixed with https://).
                          </p>
                        </div>
                      </div>
                    ))}
                  </div>
                )}
              </div>

              {/* Enable Email Lead Capture with Field Selection */}
              <div className="p-4 rounded-2xl bg-[#090A12] border border-white/[0.08] space-y-4">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="text-xs font-bold text-white">Enable Email Lead Capture</div>
                    <div className="text-[11px] text-slate-400">Collect visitor email/phone before granting product access.</div>
                  </div>
                  <input
                    type="checkbox"
                    checked={leadCaptureEnabled}
                    onChange={(e) => setLeadCaptureEnabled(e.target.checked)}
                    className="w-4 h-4 rounded text-violet-600 focus:ring-0 cursor-pointer"
                  />
                </div>

                {leadCaptureEnabled && (
                  <div className="space-y-4 pt-3 border-t border-white/[0.06]">
                    {/* Form Fields to Collect */}
                    <div>
                      <label className="block text-[11px] font-bold uppercase tracking-wider text-slate-400 mb-2">
                        Select Visitor Details to Collect:
                      </label>
                      <div className="grid grid-cols-3 gap-2 text-xs">
                        <div className="p-2.5 rounded-xl bg-[#10121E] border border-violet-500/30 text-white flex items-center gap-2">
                          <CheckSquare className="w-4 h-4 text-emerald-400 shrink-0" />
                          <span className="font-semibold text-xs">Email</span>
                        </div>

                        <button
                          type="button"
                          onClick={() => setCollectName(!collectName)}
                          className={`p-2.5 rounded-xl border flex items-center gap-2 text-xs cursor-pointer transition-all ${
                            collectName
                              ? 'bg-violet-600/20 border-violet-500 text-white'
                              : 'bg-[#10121E] border-white/[0.08] text-slate-400 hover:text-white'
                          }`}
                        >
                          {collectName ? <CheckSquare className="w-4 h-4 text-emerald-400" /> : <Square className="w-4 h-4" />}
                          <span>Full Name</span>
                        </button>

                        <button
                          type="button"
                          onClick={() => setCollectPhone(!collectPhone)}
                          className={`p-2.5 rounded-xl border flex items-center gap-2 text-xs cursor-pointer transition-all ${
                            collectPhone
                              ? 'bg-violet-600/20 border-violet-500 text-white'
                              : 'bg-[#10121E] border-white/[0.08] text-slate-400 hover:text-white'
                          }`}
                        >
                          {collectPhone ? <CheckSquare className="w-4 h-4 text-emerald-400" /> : <Square className="w-4 h-4" />}
                          <span>Phone No.</span>
                        </button>
                      </div>
                    </div>

                    {/* Lead Magnet Title (Max 25 words) */}
                    <div>
                      <div className="flex items-center justify-between mb-1">
                        <label className="text-[11px] font-medium text-slate-300">Lead Magnet / Asset Title</label>
                        <span className="text-[10px] text-slate-500">{countWords(leadMagnetTitle)}/25 words</span>
                      </div>
                      <input
                        type="text"
                        maxLength={120}
                        value={leadMagnetTitle}
                        onChange={(e) => {
                          if (countWords(e.target.value) <= 25 || e.target.value.length < leadMagnetTitle.length) {
                            setLeadMagnetTitle(e.target.value);
                          }
                        }}
                        placeholder="e.g. Free Strategy Guide & Template"
                        className="w-full px-3 py-2 rounded-xl bg-[#10121E] border border-white/[0.08] text-white text-xs placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                      />
                    </div>

                    {/* Submit Button CTA Text */}
                    <div>
                      <label className="block text-[11px] font-medium text-slate-300 mb-1">Submit Button CTA Text</label>
                      <input
                        type="text"
                        maxLength={40}
                        value={leadCaptureButtonText}
                        onChange={(e) => setLeadCaptureButtonText(e.target.value)}
                        placeholder="e.g. Get Access"
                        className="w-full px-3 py-2 rounded-xl bg-[#10121E] border border-white/[0.08] text-white text-xs placeholder:text-slate-600 focus:outline-none focus:border-violet-500"
                      />
                    </div>
                  </div>
                )}
              </div>

              {/* Primary Action Button Underneath Form */}
              <div className="pt-2">
                <button
                  type="submit"
                  disabled={saving}
                  className="w-full py-3.5 rounded-2xl bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white font-bold text-sm shadow-xl shadow-violet-600/30 flex items-center justify-center gap-2 transition-all hover:scale-[1.01] active:scale-[0.98] cursor-pointer"
                >
                  <Save className="w-4 h-4" />
                  <span>{saving ? 'Publishing Tapframe...' : 'Save & Publish QR Tapframe'}</span>
                </button>
              </div>
            </div>
          </form>
        </div>

        {/* Right Sticky Preview */}
        <div className="lg:col-span-5 sticky top-20 space-y-4">
          <div className="flex bg-[#10121E] p-1 rounded-2xl border border-white/[0.08]">
            <button
              onClick={() => setPreviewTab('mobile')}
              className={`flex-1 py-2 text-xs font-semibold rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer ${
                previewTab === 'mobile' ? 'bg-violet-600 text-white shadow' : 'text-slate-400 hover:text-white'
              }`}
            >
              <Smartphone className="w-3.5 h-3.5" />
              <span>Viewer Mobile View</span>
            </button>
            <button
              onClick={() => setPreviewTab('qr')}
              className={`flex-1 py-2 text-xs font-semibold rounded-xl flex items-center justify-center gap-1.5 transition-all cursor-pointer ${
                previewTab === 'qr' ? 'bg-violet-600 text-white shadow' : 'text-slate-400 hover:text-white'
              }`}
            >
              <Tv className="w-3.5 h-3.5" />
              <span>Video On-Screen Frame</span>
            </button>
          </div>

          <div className="p-4 rounded-3xl bg-[#10121E] border border-white/[0.08] flex flex-col items-center justify-center relative">
            <div className="mb-2">
              <Mascot 
                mood="curious" 
                size="xs" 
                badge="Co-Pilot Funnel" 
                message="Viewers enter their details to unlock instant access to your product link!" 
              />
            </div>

            {previewTab === 'mobile' ? (
              <div className="w-full max-w-[320px] rounded-[36px] bg-[#07080D] border-4 border-slate-700 shadow-2xl overflow-hidden p-4 text-center relative">
                {/* 1. Channel Header */}
                <div className="flex items-center justify-center gap-2 mb-3 pb-2 border-b border-white/[0.08]">
                  {activeChannel?.avatar_url && (
                    <img
                      src={activeChannel.avatar_url}
                      alt="Channel"
                      className="w-6 h-6 rounded-full object-cover ring-1 ring-violet-500"
                    />
                  )}
                  <span className="text-xs font-bold text-white">{activeChannel?.name || 'Creator'}</span>
                </div>

                {/* 2. Badge */}
                {badgeText && (
                  <div className="inline-block px-3 py-0.5 rounded-full bg-violet-600/30 border border-violet-500/40 text-[10px] font-bold text-violet-300 mb-2">
                    {badgeText}
                  </div>
                )}

                {/* 3. Main Headline & Subheadline */}
                <h3 className="text-sm font-bold text-white leading-tight mb-1.5">
                  {headline || 'The Six Figure Wealth Guide'}
                </h3>

                <p className="text-[11px] text-slate-400 mb-4 line-clamp-3">
                  {subheadline || 'Drop your email below to get the free downloadable guide and resources.'}
                </p>

                {/* 4. Lead Capture Form */}
                {leadCaptureEnabled ? (
                  <div className="p-3.5 rounded-2xl bg-white/[0.04] border border-violet-500/30 mb-3 space-y-2.5 text-left shadow-lg">
                    <div className="text-[10px] font-bold text-violet-300 flex items-center gap-1">
                      <Sparkles className="w-3.5 h-3.5 text-violet-400" />
                      <span>{leadMagnetTitle || 'Free Strategy Guide & Template'}</span>
                    </div>

                    {collectName && (
                      <input
                        type="text"
                        disabled
                        placeholder="Your full name..."
                        className="w-full px-2.5 py-1.5 rounded-xl bg-black/40 text-[11px] text-slate-400 border border-white/[0.08]"
                      />
                    )}

                    <input
                      type="email"
                      disabled
                      placeholder="Your email address..."
                      className="w-full px-2.5 py-1.5 rounded-xl bg-black/40 text-[11px] text-slate-400 border border-white/[0.08]"
                    />

                    {collectPhone && (
                      <input
                        type="tel"
                        disabled
                        placeholder="Your phone number..."
                        className="w-full px-2.5 py-1.5 rounded-xl bg-black/40 text-[11px] text-slate-400 border border-white/[0.08]"
                      />
                    )}

                    <button
                      type="button"
                      disabled
                      className="w-full py-2.5 rounded-2xl bg-violet-600 text-white font-bold text-xs shadow-md shadow-violet-600/30 flex items-center justify-center gap-1.5"
                    >
                      <span>{leadCaptureButtonText || 'Get Access'}</span>
                      <ArrowRight className="w-3.5 h-3.5" />
                    </button>

                    {primaryProduct?.title && (
                      <div className="text-[9px] text-slate-400 text-center pt-0.5 flex items-center justify-center gap-1">
                        <Lock className="w-2.5 h-2.5 text-emerald-400" />
                        <span>Unlocks & redirects to <strong>{primaryProduct.title}</strong></span>
                      </div>
                    )}
                  </div>
                ) : (
                  productLinks.length > 0 && (
                    <div className="space-y-1.5 mb-3">
                      {productLinks.map((link, i) => (
                        <div
                          key={i}
                          className="py-2.5 px-3 rounded-2xl bg-white/[0.08] hover:bg-white/[0.12] border border-white/[0.08] text-xs font-semibold text-slate-200 flex items-center justify-between shadow-sm"
                        >
                          <span className="truncate">{link.title || `Product Link #${i + 1}`}</span>
                          <ExternalLink className="w-3.5 h-3.5 text-violet-400 shrink-0" />
                        </div>
                      ))}
                    </div>
                  )
                )}

                <div className="mt-4 pt-3 border-t border-white/[0.08] text-[9px] text-slate-500">
                  Powered by ClearpathQR
                </div>
              </div>
            ) : (
              <div className="w-full">
                <QRCodeDisplay page={previewPage} size={180} showCardWrapper={true} />
              </div>
            )}
          </div>
        </div>
      </div>

      {/* Upgrade Paywall Modal */}
      <UpgradePaywallModal
        isOpen={showPaywallModal}
        onClose={() => setShowPaywallModal(false)}
        featureTitle={paywallReason.title}
        featureDescription={paywallReason.desc}
      />
    </div>
  );
};
